#!/usr/bin/env python3
"""Render the human-readable .progress control plane from the database.

The database is the structured source of truth; these Markdown files are the
fast visual checkpoint the user and the next session read first.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import corpus_db  # noqa: E402

ROOT = corpus_db.PROJECT_ROOT
PROGRESS = ROOT / ".progress"


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def status_counts(conn) -> dict:
    rows = conn.execute("SELECT status, count(*) n FROM repositories GROUP BY status").fetchall()
    d = {r["status"]: r["n"] for r in rows}
    d["TOTAL"] = sum(d.values())
    return d


def render(conn) -> None:
    PROGRESS.mkdir(parents=True, exist_ok=True)
    repo = status_counts(conn)
    files = conn.execute("SELECT count(*) FROM files").fetchone()[0]
    kdocs = len(list((ROOT / "data" / "scraped").rglob("*.md"))) if (ROOT / "data" / "scraped").exists() else 0
    deps = conn.execute("SELECT count(*) FROM dependencies").fetchone()[0]
    urls = conn.execute("SELECT count(*) FROM urls").fetchone()[0]
    domains = conn.execute("SELECT count(*) FROM domains").fetchone()[0]
    old_count = conn.execute("SELECT count(*) FROM old_projects").fetchone()[0]
    task_total = conn.execute("SELECT count(*) FROM tasks").fetchone()[0]
    task_pending = conn.execute("SELECT count(*) FROM tasks WHERE status='PENDING'").fetchone()[0]
    task_done = conn.execute("SELECT count(*) FROM tasks WHERE status IN ('VERIFIED','COMPLETED')").fetchone()[0]
    task_blocked = conn.execute("SELECT count(*) FROM tasks WHERE status='BLOCKED'").fetchone()[0]
    task_inprog = conn.execute("SELECT count(*) FROM tasks WHERE status='IN_PROGRESS'").fetchone()[0]
    task_dropped = conn.execute("SELECT count(*) FROM tasks WHERE status='DROPPED'").fetchone()[0]
    # Dropped work is deliberately not done, so it does not keep a phase "open".
    open_phases = [r["phase"] for r in conn.execute(
        "SELECT DISTINCT phase FROM tasks WHERE status NOT IN ('VERIFIED','COMPLETED','DROPPED') ORDER BY phase")]
    closed_phases = [r["phase"] for r in conn.execute(
        "SELECT phase FROM tasks GROUP BY phase "
        "HAVING sum(CASE WHEN status IN ('VERIFIED','COMPLETED','DROPPED') THEN 1 ELSE 0 END) = count(*) ORDER BY phase")]
    errors = conn.execute("SELECT count(*) FROM processing_errors").fetchone()[0]

    (PROGRESS / "MASTER_PROGRESS.md").write_text(f"""# MASTER PROGRESS

> Auto-generated by `scripts/progress_report.py` at {now()}. Regenerate after every checkpoint.

## Corpus

| Metric | Value |
| --- | --- |
| Old projects | {old_count} |
| Repository artifacts | {repo['TOTAL']} |
| Minimum corpus work units | {old_count + repo['TOTAL']} |
| Repositories VERIFIED | {repo.get('VERIFIED', 0)} |
| Repositories DISCOVERED (pending) | {repo.get('DISCOVERED', 0)} |
| Repositories PARTIAL | {repo.get('PARTIAL', 0)} |
| Files ingested | {files} |
| Per-file Markdown records | {kdocs} |
| Dependencies recorded | {deps} |
| URLs / domains | {urls} / {domains} |
| Processing errors logged | {errors} |

## Tasks

| Metric | Value |
| --- | --- |
| Total tasks | {task_total} |
| VERIFIED/COMPLETED | {task_done} |
| IN_PROGRESS | {task_inprog} |
| PENDING | {task_pending} |
| BLOCKED | {task_blocked} |
| DROPPED (intentionally not done) | {task_dropped} |

## Phase state (derived from the task queue)

- **Closed phases:** {', '.join(closed_phases) or 'none'}
- **Still open:** {', '.join(open_phases) or 'none'}
""" + "\n")

    (PROGRESS / "TASK_QUEUE.md").write_text("# TASK QUEUE\n\n> Auto-generated. Ordered by priority then id.\n\n"
        + "\n".join(f"- [ ] `{r['task_id']}` [{r['phase']}] {r['title']} (prio {r['priority']})"
                    for r in conn.execute("SELECT * FROM tasks WHERE status NOT IN ('VERIFIED','COMPLETED','DROPPED') ORDER BY priority, task_id LIMIT 400"))
        + "\n")

    (PROGRESS / "TASK_STATUS.md").write_text("# TASK STATUS\n\n> Auto-generated. Counts by status and phase.\n\n"
        + "## By status\n\n" + "\n".join(f"- {r['status']}: {r['n']}" for r in conn.execute("SELECT status, count(*) n FROM tasks GROUP BY status"))
        + "\n\n## By phase\n\n" + "\n".join(f"- {r['phase']}: {r['n']}" for r in conn.execute("SELECT phase, count(*) n FROM tasks GROUP BY phase ORDER BY phase"))
        + "\n\n## Open (not complete, not blocked)\n\n" + (
            "\n".join(f"- [{r['status']}] `{r['task_id']}` {r['title']}"
                      for r in conn.execute("SELECT * FROM tasks WHERE subject_kind IS NULL AND status NOT IN ('VERIFIED','COMPLETED','DROPPED')") )
            or "_None._")
        + "\n")

    # Blocked work is not the next actionable task, so it is listed separately.
    pending = conn.execute("SELECT * FROM tasks WHERE status NOT IN ('VERIFIED','COMPLETED','BLOCKED','DROPPED') ORDER BY priority, task_id LIMIT 1").fetchone()
    blocked = list(conn.execute("SELECT * FROM tasks WHERE status='BLOCKED' ORDER BY priority, task_id"))
    blocked_md = "\n".join(f"- `{b['task_id']}` {b['title']}" for b in blocked) or "_None._"
    (PROGRESS / "CURRENT_TASK.md").write_text(
        f"""# CURRENT TASK

- **task_id:** `{pending['task_id'] if pending else '—'}`
- **phase:** {pending['phase'] if pending else '—'}
- **title:** {pending['title'] if pending else 'no open tasks'}
- **status:** {pending['status'] if pending else '—'}
- **updated_at:** {now()}
- **machine:** {__import__('os').uname().nodename}

## Blocked (not the next action)

{blocked_md}
""")

    (PROGRESS / "CONTINUATION_PROMPT.md").write_text(f"""# CONTINUATION PROMPT

If a new session starts and the only user message is `continue`:

1. Read `.progress/CONTINUATION_PROMPT.md`, `.progress/MASTER_PROGRESS.md`,
   `.progress/CURRENT_TASK.md`, `.progress/TASK_QUEUE.md`, `.progress/ERRORS.md`.
2. Inspect actual filesystem and DB state:
   `python3 scripts/progress_report.py` and query `data/database/trading_ai_corpus.sqlite`.
3. Find the highest-priority incomplete task with satisfied dependencies.
4. Verify whether any stale IN_PROGRESS task actually completed
   (`SELECT * FROM repositories WHERE status='DISCOVERED'`).
5. Resume the nearest missing stage:
   - extraction pending  -> `python3 scripts/corpus_extract.py`
   - product build       -> continue in `apps/web/` (Phases 13-15)
6. Update the checkpoint and continue. Never redo verified work.

Last rendered: {now()}
Next exact action: resume `{pending['task_id'] if pending else 'none'}`.
""")

    (PROGRESS / "ERRORS.md").write_text("# ERRORS\n\n> Auto-generated. Latest 100 processing errors.\n\n"
        + "\n".join(f"- [{r['stage']}] `{r['subject_id']}`: {r['message']}"
                    for r in conn.execute("SELECT * FROM processing_errors ORDER BY error_id DESC LIMIT 100"))
        + ("\n\n_None._\n" if errors == 0 else "\n"))

    (PROGRESS / "KNOWN_LIMITATIONS.md").write_text("""# KNOWN LIMITATIONS

- Corpus extraction runs single-process on this 6-core AMD FX-6100; concurrency
  tuning is deliberately conservative to protect the ~15 GB SSD and 17 GB RAM.
- Bulk extraction data lives on the HDD at `/mnt/private-ai-data/trading-ai-extractions`.
- No GPU on this Linux host; GPU-heavy tasks must target the Windows machine or
  remain CPU-only.
- Nested-archive recursion is limited to depth 1 by default.
- Text content is truncated at 200 KB per file in the DB and FTS index.
- The distributed Windows worker is not yet connected (checked in Phase 10).
- There is no background-job system in the app, so the "background tasks" test
  category does not apply; long-running work would need to be added first.
- `npm audit --audit-level=high` is clean (exit 0), but `npm audit` reports **9
  moderate** advisories — all one chain rooted in `uuid` <11.1.1, pulled in by
  `@metamask/sdk` → `@wagmi/connectors` (wallet sign-in). It is unreachable from
  this app and its only fix is the semver-major `wagmi` 3, which RainbowKit 2 does
  not support, so it is an accepted moderate recorded in
  `docs/DEPENDENCY_AUDIT.md`. Phase 15-002 did clear the earlier critical/high set:
  `next` upgraded to 16.4.0, `vitest` to 5, and a `deepmerge-ts@^8` override closes
  the Prisma CLI chain.
- The production session-secret guard is lazy: it triggers only when a session
  token is signed or verified. A route that never reads the session (e.g. `/`)
  still responds normally with a weak secret; login/session routes fail closed.
- Shell environment variables take precedence over `apps/web/.env` at runtime, so
  an operator can override the file value by exporting `SESSION_SECRET`.
- The production Docker image has not been built in this environment (Docker is
  not installed here); the first build should be smoke-checked on a Docker host.
  See `docs/DEPLOYMENT.md`.
- Sign-in is wallet-based (SIWE), so the e2e suite cannot complete a real sign-in:
  CI has no wallet extension and no demo wallet is provided (a deliberate choice).
  The e2e specs mint a session cookie with the app's own signer for a seeded or
  throwaway account, and `tests/e2e/login-wallet.spec.ts` asserts the sign-in
  surface. The SIWE signature path itself is covered by the integration suite with
  real signatures (valid, replayed, wrong domain, wrong signer, unknown nonce).
- The WalletConnect/QR connector is only offered when
  `NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID` is set: with a placeholder, Reown rejects
  the origin and every page logs a console error. Empty is a supported mode
  (injected wallets only).
- Real execution is **on by default**: `REAL_EXECUTOR_IMPLEMENTED` is true and the
  Coinbase EVM swap venue adapter can move real funds once custody is configured and
  the kill switch is clear. It is refused (never replaced by a practice flow) whenever
  custody is unavailable or `MAINNET_EXECUTION_ENABLED=0`, and a practice (`SANDBOX`)
  session never reaches a real path (docs/NETWORK_BOUNDARY.md).
- Custody (`PHASE18-004`) is implemented: `src/lib/custody/` enforces
  per-transaction/daily spend limits and resolves a signer from the `coinbase-cdp`
  backend (Coinbase CDP Server Wallets — the wallet key stays in the provider; the app
  holds only API credentials), so `REAL_CUSTODY_IMPLEMENTED` is `true`. It fails
  closed when unconfigured, so a deployment without the `CDP_*` credentials (and
  `CDP_WALLET_SECRET` in particular) refuses every mainnet money action. Key
  rotation/audit trail, a persisted rolling spend ledger (today
  `authorizeCustodySpend()` takes `spentTodayCents` from the caller) and compliance
  (KYC/AML, sanctions, jurisdiction gating) remain follow-ups.
- The wallet-auth migration is **breaking**: it drops `User.email`/`passwordHash`
  and requires `walletAddress`, so it cannot carry existing accounts. Any existing
  deployment (including the Vercel + Tiger Cloud one) must run
  `npm run db:deploy` and `npm run db:seed` — and will lose its old accounts —
  before the new code is served. Do not deploy the wallet-auth build to an
  un-migrated database.
""")

    (PROGRESS / "PROMPT_TODO_CHECKLIST.md").write_text(
        "# PROMPT / TODO CHECKLIST\n\n"
        f"> Auto-generated from the task queue at {now()}.\n"
        f"> Authoritative task count: {task_total} (old {old_count} + repo {repo['TOTAL']} + phase tasks).\n\n"
        + "\n".join(
            f"- [{'x' if r['status'] in ('VERIFIED', 'COMPLETED') else '~' if r['status'] == 'IN_PROGRESS' else '-' if r['status'] == 'DROPPED' else ' '}] "
            f"`{r['task_id']}` [{r['phase']}] {r['title']}"
            for r in conn.execute("SELECT * FROM tasks ORDER BY phase, task_id LIMIT 250")
        )
        + "\n"
    )

    log = PROGRESS / "SESSION_LOG.md"
    entry = (
        f"\n## {now()}\n\n"
        f"- machine: {__import__('os').uname().nodename}\n"
        f"- repos VERIFIED: {repo.get('VERIFIED', 0)} / {repo['TOTAL']}\n"
        f"- files ingested: {files}, knowledge records: {kdocs}\n"
        f"- tasks VERIFIED: {task_done} / {task_total}\n"
        f"- next: {pending['task_id'] if pending else 'none'} — {pending['title'] if pending else ''}\n"
    )
    if not log.exists():
        log.write_text("# SESSION LOG\n\n> Appended by `scripts/progress_report.py`." + entry)
    else:
        log.write_text(log.read_text() + entry)

    # Preserve DECISIONS.md if it already has content, else write a starter.
    dec = PROGRESS / "DECISIONS.md"
    if not dec.exists():
        dec.write_text("# DECISIONS\n\n- D1: Reuse `old/crypto-portal` (Next.js 16 + Prisma + wagmi) as the fintech base rather than rebuilding.\n- D2: Store corpus state in a single SQLite database; per-repo mirrors under `data/database/repos/`.\n- D3: Bulk extraction on the HDD, active development on the SSD.\n- D4: No GitHub/Vercel publish until explicit authorization.\n")
    elif "Last rendered" not in dec.read_text():
        dec.write_text(dec.read_text() + f"\n\n_Last rendered: {now()}_\n")


if __name__ == "__main__":
    c = corpus_db.init_db()
    render(c)
    print(f"rendered .progress at {now()}")
    c.close()
